/*

 TETRIS_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Johnel\Desktop\GBDevTools\Tools\TileDesigner\tetris.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define tetris_mapWidth 20
#define tetris_mapHeight 18
#define tetris_mapBank 0

extern unsigned char tetris_map[];

/* End of TETRIS_MAP.H */
